# .pre-commit-config.yaml
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        entry: markdownlint --disable MD013
        files: \.(md|markdown)$

  - repo: https://github.com/errata-ai/vale
    rev: v3.0.2
    hooks:
      - id: vale
        exclude: "^"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args: ["--terragrunt-working-dir=infra"]

  - repo: local
    hooks:
      - id: dbt-compile
        name: "dbt compile"
        entry: bash -c "dbt compile --project-dir pipelines --profiles-dir pipelines --target duckdb"
        language: system
        files: '^pipelines/'
