# .pre-commit-config.yaml
repos:
  # --- Git commit-message lint -------------------------------------------
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint        # Validate conventional commit style

  # --- Markdown lint (Node CLI) ------------------------------------------
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        entry: markdownlint --disable MD013   # disable long-line rule
        files: \.(md|markdown)$

  # --- Vale prose style (run manually) -----------------------------------
  - repo: https://github.com/errata-ai/vale
    rev: v3.0.2
    hooks:
      - id: vale
        # Exclude everything by default; run with `pre-commit run vale`.
        exclude: "^"

  # --- Terraform fmt (temporarily skipped) -------------------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.0
    hooks:
      - id: terraform_fmt
        # Flat-root refactor is WIP → skip until directory structure stabilises.
        exclude: "^$"

  # --- Local dbt compile hook (manual only) ------------------------------
  - repo: local
    hooks:
      - id: dbt-compile
        name: dbt compile
        language: python          # pre-commit will create a venv with Python
        entry: dbt compile --no-write-json
        stages: [manual]          # runs only when invoked manually
        additional_dependencies:
          - dbt-core==1.9.4
          - dbt-duckdb
