version: "3.9"
services:
  spark:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - MINIO_ENDPOINT=http://minio:9000
    ports:
      - "4040:4040"
    volumes:
      - ./data:/data
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio:/data
