# ci_infracost.yml

name: ci_infracost

on:
  pull_request:
    paths: [ "infra/**/*.tf" ]
  push:
    branches: [ main ]
    paths:   [ "infra/**/*.tf" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  infracost:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    steps:
      - uses: actions/download-artifact@v4       # plan from ci_guard
        with:
          name: tfplan-json
          path: .

      # ---------- install Infracost ----------
      - uses: infracost/actions/setup@v2
        with:
          infracost_version: v0.10.33

      # ---------- scan ----------
      - name: Infracost scan
        id: scan
        uses: infracost/actions/scan@v2
        with:
          plan-file: plan.json
          format: json
          output-file: infracost.json

      # ---------- comment on PR / commit ----------
      - name: Infracost comment
        uses: infracost/actions/comment@v2
        with:
          path: infracost.json
          behavior: update

      # ---------- cost guard ----------
      - name: Fail if monthly diff > $5
        run: |
          DIFF=$(infracost output --path infracost.json --format json | jq -r '.diffTotalMonthlyCost')
          THRESHOLD=5
          echo "diff = $DIFF USD"
          if (( $(echo "$DIFF > $THRESHOLD" | bc -l) )); then
            echo "::error ::Cost increase $DIFF exceeds $THRESHOLD"
            exit 1
          fi
