# ci_plan_apply.yml

name: ci_plan_apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  apply-dev:
    uses: ./.github/workflows/terraform_apply.yml
    with:
      bucket:      ${{ vars.STATE_BUCKET }}
      state_key:   ci/terraform.tfstate
      lock_table:  ${{ vars.LOCK_TABLE }}
      workspace:   dev
      extra_var:   env=dev
      prefix:      starter-lh
      env_name:    dev
    secrets:
      budget_email: ${{ secrets.BUDGET_EMAIL }}

  apply-prod:
    if: github.ref == 'refs/heads/main'
    needs: apply-dev
    uses: ./.github/workflows/terraform_apply.yml
    with:
      bucket:      ${{ vars.STATE_BUCKET }}
      state_key:   prod/terraform.tfstate
      lock_table:  ${{ vars.LOCK_TABLE }}
      workspace:   prod
      extra_var:   env=prod
      prefix:      starter-lh
      env_name:    prod
    secrets:
      budget_email: ${{ secrets.BUDGET_EMAIL }}
      