# terraform.yml

name: terraform_template

<<<<<<< HEAD
=======
name: 'Terraform'

# on:
#  push:
#    branches: [ $default-branch ]
#  pull_request:

env:
  TF_VAR_budget_email: ${{ secrets.BUDGET_EMAIL }}

# reusable workflow trigger
>>>>>>> 2ce50b2 (chore(terraform): retrieve budget email address from env var)
on:
  workflow_call:
    inputs:
      path:        { type: string,  required: true }
      prefix:      { type: string,  required: true }
      env_name:    { type: string,  required: true }
      aws_region:  { type: string,  default: "us-east-1" }
    secrets:
      budget_email:  { required: true }
      role_to_assume: { required: true }

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache
    steps:
      - uses: actions/checkout@v4

      # ---------- cache plugins ----------
      - uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ${{ inputs.path }}/.terraform
          key: ${{ runner.os }}-tf-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.path)) }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.x
          terraform_wrapper: false

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role_to_assume }}
          aws-region:     ${{ inputs.aws_region }}

<<<<<<< HEAD
      - name: Terraform init
        run: |
          terraform -chdir=${{ inputs.path }} init \
            -backend-config="bucket=${{ vars.STATE_BUCKET }}" \
            -backend-config="key=ci/${{ inputs.env_name }}.tfstate" \
            -backend-config="dynamodb_table=${{ vars.LOCK_TABLE }}" \
            -backend-config="region=${{ inputs.aws_region }}"
=======
    # Generates an execution plan for Terraform
    - name: Terraform Plan
    #  run: terraform plan -input=false
      run: terraform -chdir=${{ inputs.path }} plan -no-color -input=false
>>>>>>> 2ce50b2 (chore(terraform): retrieve budget email address from env var)

      - name: Terraform fmt
        run: terraform -chdir=${{ inputs.path }} fmt -check -recursive

      - name: Terraform plan
        env:
          TF_VAR_prefix:        ${{ inputs.prefix }}
          TF_VAR_env:           ${{ inputs.env_name }}
          TF_VAR_budget_email:  ${{ secrets.budget_email }}
        run: terraform -chdir=${{ inputs.path }} plan -no-color -input=false -out=tfplan

      - name: Export plan.json for downstream jobs
        run: terraform -chdir=${{ inputs.path }} show -json tfplan > plan.json

      - uses: actions/upload-artifact@v4
        with:
          name: plan-json
          path: plan.json
