# .github/workflows/build-and-push.yml
name: Build & Push DevContainer image

permissions:
  contents: read
  packages: write

on:
  push:
    paths: [.devcontainer/**, .github/workflows/build-and-push.yml]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/lakehouse-code
          push: always
