# .github/workflows/build-push.yml
name: Build & Push DevContainer image

on:
  push:
    paths: [.devcontainer/**, .github/workflows/build-and-push.yml]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/lakehouse-code
          push: always
