# ====================================================================
# File: .github/workflows/ci-guard.yml
# Purpose: Enforce PR label gate and run IaC + security checks
# ====================================================================

name: guard-ci

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  push:
    branches: [ main ]

jobs:
  iac-guard-pr:
    if: github.event_name == 'pull_request' &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'environment:') &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'norm:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common

      - name: Run terraform fmt (check)
        run: terraform fmt -recursive -check

      - name: Terraform validate
        run: terraform init -backend=false && terraform validate

      - name: Run tfsec
        run: tfsec --config-file .tfsec.yml

      - name: Run tflint
        run: |
          tflint --init
          tflint

  iac-guard-main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common

      - name: Run terraform fmt (check)
        run: terraform fmt -recursive -check

      - name: Terraform validate
        run: terraform init -backend=false && terraform validate

      - name: Run tfsec
        run: tfsec --config-file .tfsec.yml

      - name: Run tflint
        run: |
          tflint --init
          tflint

      # --- SBOM / cosign / GE stubs --------------------------------
      - name: Generate SBOM (stub)
        run: echo "Syft SBOM generation stub"

      - name: Sign SBOM with cosign (stub)
        run: echo "cosign sign stub"

      - name: Great Expectations data contract (stub)
        run: echo "GE contract check stub"
