# c-infracost.yml

name: infracost-ci

on:
  pull_request:
    paths: [ "**/*.tf", ".github/workflows/ci-deploy.yml" ]
  push:
    branches: [ main ]
    paths: [ "**/*.tf", ".github/workflows/ci-deploy.yml" ]

jobs:
  infracost-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Breakdown
        run: |
          infracost breakdown --path=infra \
            --format=json \
            --out-file=/tmp/infracost.json

      - name: Post cost comment
        if: github.event_name == 'pull_request'
        run: |
          infracost comment github \
            --path=/tmp/infracost.json \
            --behavior=update \
            --repo=${{ github.repository }} \
            --pull-request=${{ github.event.pull_request.number }} \
            --github-token=${{ github.token }}
