# ====================================================================
# File: .github/workflows/ci_guard.yml
# Purpose: One-job guard – PR gated by labels, main always runs
# ====================================================================

name: ci_guard

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  push:
    branches: [ main ]

jobs:
  iac-guard:
    # ---------------------------------------------------------------
    # Job condition:
    #   • push  → always run
    #   • pull_request → run only if both required labels are present
    # ---------------------------------------------------------------
    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'environment:') &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'norm:')
      )
    runs-on: ubuntu-latest

    steps:
    # --- Common setup ---------------------------------------------
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4       # stable as of 2025-05

      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.51.1         # latest as of 2025-05

    # --- Common IaC checks ----------------------------------------
      - name: terraform fmt (check)
        run: terraform fmt -recursive -check

      - name: terraform validate
        run: terraform init -backend=false && terraform validate

      - name: tflint
        run: |
          tflint --init
          tflint

      - uses: aquasecurity/tfsec-action@v1.0.1
        with:
          version: latest                 # always download latest tfsec CLI
          additional_args: --config-file .tfsec.yml --soft-fail

    # --- main-only steps ------------------------------------------
      - name: Generate SBOM (stub)
        if: github.event_name == 'push'
        run: echo "Syft SBOM generation stub"

      - name: Sign SBOM with cosign (stub)
        if: github.event_name == 'push'
        run: echo "cosign sign stub"

      - name: Great Expectations data contract (stub)
        if: github.event_name == 'push'
        run: echo "GE contract check stub"
