name: ci_plan_apply
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  tf_plan_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Plan
        run: |
          terraform -chdir=infra plan \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}" \
            -input=false -out=tf.plan
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform -chdir=infra apply -input=false -auto-approve tf.plan
