name: ci_plan_apply
on:
  workflow_call:
    inputs:
      env:            # dev / prod / etc.
        required: true
        type: string

jobs:
  tf_plan_apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform -chdir=infra init 

      - name: Terraform Plan
        run: |
          terraform -chdir=infra plan \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}" \
            -input=false -out=tf.plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform -chdir=infra apply -input=false -auto-approve tf.plan
