name: ci_smoke
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Spin up Spark demo
        run: |
          docker compose -f spark_demo/docker_compose.yaml up -d
          sleep 30
      - name: Run demo queries
        run: spark_demo/run_demo_queries.sh
