name: deploy

# Manual trigger and automatic trigger on pushes to main
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  apply:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      id-token: write        # allow OIDC token retrieval
      contents: read         # checkout needs this (defaults to read)

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- OIDC → AssumeRole ---
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION || 'us-east-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        run: |
          cd infra
          terraform init -input=false
          start=$(date +%s)
          terraform apply -auto-approve -input=false \
            -var="budget_email=${{ secrets.BUDGET_EMAIL }}"
          end=$(date +%s)
          echo "{\"runtime_sec\":$((end-start))}" > /tmp/stopwatch.json

      - name: Upload stopwatch artifact
        uses: actions/upload-artifact@v4
        with:
          name: stopwatch
          path: /tmp/stopwatch.json
