name: Guard CI

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  guard:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'environment:')
        && contains(join(github.event.pull_request.labels.*.name, ','), 'norm:')
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
   