# ====================================================================
# File: .github/workflows/infra.yml
# Purpose: Build SBOM → cosign sign → run Great Expectations checks
# ====================================================================
name: Infra Guard

on:
  pull_request:
    paths: [ 'infra/**', 'pipelines/**' ]
    types: [opened, synchronize, labeled]

jobs:
  infra:
    if: >-
      contains(join(github.event.pull_request.labels.*.name, ','), 'environment:') &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'norm:')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: "Run common setup"
        uses: ./.github/actions/common

      - name: "Generate SBOM (stub)"
        run: echo "Syft SBOM generation stub"

      - name: "Sign SBOM with cosign (stub)"
        run: echo "cosign sign stub"

      - name: "Great Expectations data contract (stub)"
        run: echo "GE contract check stub"
