# .github/workflows/smoke.yml
name: Smoke Test

on:
  push:
    branches: [ main ]
    paths: [ 'quick-start.sh', '**/docker-compose*', 'Makefile' ]
  pull_request:
    paths: [ 'quick-start.sh', '**/smoke.yml', '**/docker-compose*', 'Makefile' ]
  workflow_dispatch:

jobs:
  smoke:
    if: github.event_name != 'pull_request' ||
        !contains(join(github.event.pull_request.labels.*.name, ','), 'skip-smoke')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/actions/common

      - name: Run smoke script
        run: |
          chmod +x ./quick-start.sh
          ./quick-start.sh --smoke --local-mode

      - name: Smoke summary
        if: always()
        run: |
          echo "### Smoke Test Result" >> $GITHUB_STEP_SUMMARY
          echo "Workflow: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
