name: Smoke Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/lakehouse-code:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run quick-start smoke
        run: ./quick-start.sh --smoke --local-mode
