name: tf_fmt_validate
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: infra
jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - run: terraform -chdir=${{ inputs.path }} fmt -check -recursive
      - run: terraform -chdir=${{ inputs.path }} validate -no-color
